name: Generate Profile Cards

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: osmanveyetkin
          THEME: zenburn
          UTC_OFFSET: 3
          AUTO_PUSH: false

      - name: Push to output-cards branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-cards
          build_dir: profile-summary-card-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
